### ISSUE TITLE
[Firefox] Anoying additional spacing in each message box

### ISSUE THREAD

**Issue by skullmasher** [heartless-gaming/ezChat#21]
Even worse on Firefox ESR (v45.8.0).
![screenshot - 04112017 - 11 11 40 am](https://cloud.githubusercontent.com/assets/4488386/24901607/e9f2e5de-1ea7-11e7-8c07-834603faf2cd.png)
Screened on Debian 8 Jessie.

**Comment by DanGeffroy** [comment]
:croissant:  :computer: :coffee:
