### ISSUE TITLE
welp, you can inject html :S

### ISSUE THREAD

**Issue by DanGeffroy** [heartless-gaming/ezChat#27]
Thanks to this line :  '[innerHTML]="message.text | linky | emojify"'

line 30 of app.component.html

:cry:

**Comment by skullmasher** [comment]
![ezchat_xss](https://cloud.githubusercontent.com/assets/4488386/25021036/0535e248-2091-11e7-84cc-346f8d4b72c5.png)

Angular strips `<script>` but not `<h1>` and stuff. More at https://angular.io/docs/ts/latest/guide/security.html#xss). My bad for not trying other html tag some days ago.

I'm pretty sure [htmlspecialchars](http://us.php.net/htmlspecialchars) from PHP exists in node.

**Comment by skullmasher** [comment]
Fixed in d5a9ed4223934ac7aa2eead7d3053e6b9f9d67ef Lodash got an escape function !
